// Re-export game event types from @mud/redis-client
export type {
  BaseGameEvent,
  PlayerSpawnEvent,
  PlayerMoveEvent,
  PlayerActivityEvent,
  PlayerDeathEvent,
  PlayerRespawnEvent,
  PlayerLevelUpEvent,
  PlayerJoinPartyEvent,
  PlayerLeavePartyEvent,
  LootSpawnEvent,
  CombatStartEvent,
  CombatHitEvent,
  CombatMissEvent,
  CombatEndEvent,
  CombatInitiateEvent,
  MonsterSpawnEvent,
  MonsterMoveEvent,
  MonsterEncounterEvent,
  MonsterDeathEvent,
  NpcDialogueEvent,
  NpcQuestOfferEvent,
  PartyCreateEvent,
  PartyDisbandEvent,
  WeatherChangeEvent,
  TimeTickEvent,
  GameEvent,
  GameEventType,
  EventListener,
} from '@mud/redis-client';
