import { BiomeInfo } from './world/types';

export const BIOMES: Record<string, BiomeInfo> = {
  OCEAN: {
    id: 1,
    name: 'Ocean',
    description: 'Deep blue waters',
    color: '#4c5aa4',
    ascii: '~',
  },
  SHALLOW_OCEAN: {
    id: 2,
    name: 'Shallow Ocean',
    description: 'Light blue coastal waters',
    color: '#4f64c9',
    ascii: '≈',
  },
  BEACH: {
    id: 3,
    name: 'Beach',
    description: 'Sandy coastline',
    color: '#f8d796',
    ascii: '.',
  },
  DESERT: {
    id: 4,
    name: 'Desert',
    description: 'Hot, dry sands',
    color: '#f7dc6f',
    ascii: 'd',
  },
  GRASSLAND: {
    id: 5,
    name: 'Grassland',
    description: 'Rolling green plains',
    color: '#61a84d',
    ascii: 'g',
  },
  FOREST: {
    id: 6,
    name: 'Forest',
    description: 'Dense woodland',
    color: '#3b8632',
    ascii: 'T',
  },
  JUNGLE: {
    id: 7,
    name: 'Jungle',
    description: 'Tropical rainforest',
    color: '#1e8449',
    ascii: 'J',
  },
  SWAMP: {
    id: 8,
    name: 'Swamp',
    description: 'Murky wetlands',
    color: '#52c41a',
    ascii: 'S',
  },
  LAKE: {
    id: 9,
    name: 'Lake',
    description: 'Fresh water lake',
    color: '#3498db',
    ascii: 'L',
  },
  RIVER: {
    id: 10,
    name: 'River',
    description: 'Flowing water',
    color: '#5dade2',
    ascii: 'r',
  },
  TUNDRA: {
    id: 11,
    name: 'Tundra',
    description: 'Cold, barren land',
    color: '#a8a8fd',
    ascii: 't',
  },
  TAIGA: {
    id: 12,
    name: 'Taiga',
    description: 'Northern coniferous forest',
    color: '#196f3d',
    ascii: 'P',
  },
  MOUNTAIN: {
    id: 13,
    name: 'Mountain',
    description: 'Rocky peaks',
    color: '#533e1a',
    ascii: '^',
  },
  SNOWY_MOUNTAIN: {
    id: 14,
    name: 'Snowy Mountain',
    description: 'Snow-capped peaks',
    color: '#e2e1de',
    ascii: 'A',
  },
  HILLS: {
    id: 15,
    name: 'Hills',
    description: 'Rolling hills',
    color: '#a9dfbf',
    ascii: 'h',
  },
  SAVANNA: {
    id: 16,
    name: 'Savanna',
    description: 'Tropical grassland',
    color: '#98cb2a',
    ascii: 's',
  },
  ALPINE: {
    id: 17,
    name: 'Alpine',
    description: 'High mountain meadows',
    color: '#abebc6',
    ascii: 'a',
  },
  VOLCANIC: {
    id: 18,
    name: 'Volcanic',
    description: 'Active volcanic region',
    color: '#e74c3c',
    ascii: 'V',
  },
};
