services:
  postgres:
    image: postgres:15
    container_name: mud_postgres
    environment:
      POSTGRES_USER: mud
      POSTGRES_PASSWORD: mudpassword
      POSTGRES_DB: mud_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: mud_redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  nginx:
    image: nginx:latest
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '80:80'
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  # certbot removed - TLS is handled by the Google HTTPS Load Balancer
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
