version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: mud_postgres
    environment:
      POSTGRES_USER: mud
      POSTGRES_PASSWORD: mudpassword
      POSTGRES_DB: mud_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
