-- CreateTable
CREATE TABLE `GameState` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tick` INTEGER NOT NULL DEFAULT 0,
    `gameHour` INTEGER NOT NULL DEFAULT 0,
    `gameDay` INTEGER NOT NULL DEFAULT 1,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
