import { ItemType, PlayerSlot } from '@mud/database';
import type { ItemTemplateSeed } from './item-types';

const ARMOR_TEMPLATES: ItemTemplateSeed[] = [
  {
    name: 'Threadbare Hood',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. A cloth hood shielding the eyes.',
    value: 2,
    defense: 1,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 12,
    slot: PlayerSlot.head,
  },
  {
    name: 'Threadbare Circlet',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. A circlet lined with thin plates.',
    value: 6,
    defense: 2,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 10.8,
    slot: PlayerSlot.head,
  },
  {
    name: 'Threadbare Helm',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. A rigid helm forged for battle.',
    value: 10,
    defense: 3,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 9.0,
    slot: PlayerSlot.head,
  },
  {
    name: 'Threadbare Tunic',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Layered fabrics stitched again and again.',
    value: 6,
    defense: 1,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 12,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Threadbare Jack',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Quilted layers reinforced with studs.',
    value: 10,
    defense: 2,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 10.8,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Threadbare Cuirass',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Rigid plates locked over a padded core.',
    value: 14,
    defense: 3,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 9.0,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Threadbare Wraps',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Cloth wraps tightened for every expedition.',
    value: 4,
    defense: 1,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 12,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Threadbare Bracers',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Leather bracers backed with metal.',
    value: 7,
    defense: 2,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 10.8,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Threadbare Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Full gauntlets guarding every finger.',
    value: 11,
    defense: 3,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 9.0,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Threadbare Boots',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Boots with extra stitching for long marches.',
    value: 5,
    defense: 1,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 12,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Threadbare Greaves',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Fitted greaves with hidden plates.',
    value: 8,
    defense: 2,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 10.8,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Threadbare Chausses',
    type: ItemType.ARMOR,
    description:
      'Patched gear barely holding together. Segmented armor that guards every stride.',
    value: 12,
    defense: 3,
    rarity: 'Poor',
    rank: 1,
    dropWeight: 9.0,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Travelworn Hood',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. A cloth hood shielding the eyes.',
    value: 6,
    defense: 2,
    rarity: 'Common',
    rank: 2,
    dropWeight: 11,
    slot: PlayerSlot.head,
  },
  {
    name: 'Travelworn Circlet',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. A circlet lined with thin plates.',
    value: 10,
    defense: 3,
    rarity: 'Common',
    rank: 2,
    dropWeight: 9.9,
    slot: PlayerSlot.head,
  },
  {
    name: 'Travelworn Helm',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. A rigid helm forged for battle.',
    value: 14,
    defense: 4,
    rarity: 'Common',
    rank: 2,
    dropWeight: 8.25,
    slot: PlayerSlot.head,
  },
  {
    name: 'Travelworn Tunic',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Layered fabrics stitched again and again.',
    value: 10,
    defense: 2,
    rarity: 'Common',
    rank: 2,
    dropWeight: 11,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Travelworn Jack',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Quilted layers reinforced with studs.',
    value: 14,
    defense: 3,
    rarity: 'Common',
    rank: 2,
    dropWeight: 9.9,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Travelworn Cuirass',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Rigid plates locked over a padded core.',
    value: 18,
    defense: 4,
    rarity: 'Common',
    rank: 2,
    dropWeight: 8.25,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Travelworn Wraps',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Cloth wraps tightened for every expedition.',
    value: 8,
    defense: 2,
    rarity: 'Common',
    rank: 2,
    dropWeight: 11,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Travelworn Bracers',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Leather bracers backed with metal.',
    value: 11,
    defense: 3,
    rarity: 'Common',
    rank: 2,
    dropWeight: 9.9,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Travelworn Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Full gauntlets guarding every finger.',
    value: 15,
    defense: 4,
    rarity: 'Common',
    rank: 2,
    dropWeight: 8.25,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Travelworn Boots',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Boots with extra stitching for long marches.',
    value: 9,
    defense: 2,
    rarity: 'Common',
    rank: 2,
    dropWeight: 11,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Travelworn Greaves',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Fitted greaves with hidden plates.',
    value: 12,
    defense: 3,
    rarity: 'Common',
    rank: 2,
    dropWeight: 9.9,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Travelworn Chausses',
    type: ItemType.ARMOR,
    description:
      'Reliable protection for fledgling adventurers. Segmented armor that guards every stride.',
    value: 16,
    defense: 4,
    rarity: 'Common',
    rank: 2,
    dropWeight: 8.25,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Militia Hood',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. A cloth hood shielding the eyes.',
    value: 12,
    defense: 3,
    rarity: 'Common',
    rank: 3,
    dropWeight: 10,
    slot: PlayerSlot.head,
  },
  {
    name: 'Militia Circlet',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. A circlet lined with thin plates.',
    value: 16,
    defense: 4,
    rarity: 'Common',
    rank: 3,
    dropWeight: 9.0,
    slot: PlayerSlot.head,
  },
  {
    name: 'Militia Helm',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. A rigid helm forged for battle.',
    value: 20,
    defense: 5,
    rarity: 'Common',
    rank: 3,
    dropWeight: 7.5,
    slot: PlayerSlot.head,
  },
  {
    name: 'Militia Tunic',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Layered fabrics stitched again and again.',
    value: 16,
    defense: 3,
    rarity: 'Common',
    rank: 3,
    dropWeight: 10,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Militia Jack',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Quilted layers reinforced with studs.',
    value: 20,
    defense: 4,
    rarity: 'Common',
    rank: 3,
    dropWeight: 9.0,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Militia Cuirass',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Rigid plates locked over a padded core.',
    value: 24,
    defense: 5,
    rarity: 'Common',
    rank: 3,
    dropWeight: 7.5,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Militia Wraps',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Cloth wraps tightened for every expedition.',
    value: 14,
    defense: 3,
    rarity: 'Common',
    rank: 3,
    dropWeight: 10,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Militia Bracers',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Leather bracers backed with metal.',
    value: 17,
    defense: 4,
    rarity: 'Common',
    rank: 3,
    dropWeight: 9.0,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Militia Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Full gauntlets guarding every finger.',
    value: 21,
    defense: 5,
    rarity: 'Common',
    rank: 3,
    dropWeight: 7.5,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Militia Boots',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Boots with extra stitching for long marches.',
    value: 15,
    defense: 3,
    rarity: 'Common',
    rank: 3,
    dropWeight: 10,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Militia Greaves',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Fitted greaves with hidden plates.',
    value: 18,
    defense: 4,
    rarity: 'Common',
    rank: 3,
    dropWeight: 9.0,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Militia Chausses',
    type: ItemType.ARMOR,
    description:
      'Standard kit used in remote outposts. Segmented armor that guards every stride.',
    value: 22,
    defense: 5,
    rarity: 'Common',
    rank: 3,
    dropWeight: 7.5,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Tempered Hood',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. A cloth hood shielding the eyes.',
    value: 24,
    defense: 4,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 9,
    slot: PlayerSlot.head,
  },
  {
    name: 'Tempered Circlet',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. A circlet lined with thin plates.',
    value: 28,
    defense: 5,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 8.1,
    slot: PlayerSlot.head,
  },
  {
    name: 'Tempered Helm',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. A rigid helm forged for battle.',
    value: 32,
    defense: 6,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 6.75,
    slot: PlayerSlot.head,
  },
  {
    name: 'Tempered Tunic',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Layered fabrics stitched again and again.',
    value: 28,
    defense: 4,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 9,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Tempered Jack',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Quilted layers reinforced with studs.',
    value: 32,
    defense: 5,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 8.1,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Tempered Cuirass',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Rigid plates locked over a padded core.',
    value: 36,
    defense: 6,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 6.75,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Tempered Wraps',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Cloth wraps tightened for every expedition.',
    value: 26,
    defense: 4,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 9,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Tempered Bracers',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Leather bracers backed with metal.',
    value: 29,
    defense: 5,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 8.1,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Tempered Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Full gauntlets guarding every finger.',
    value: 33,
    defense: 6,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 6.75,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Tempered Boots',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Boots with extra stitching for long marches.',
    value: 27,
    defense: 4,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 9,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Tempered Greaves',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Fitted greaves with hidden plates.',
    value: 30,
    defense: 5,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 8.1,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Tempered Chausses',
    type: ItemType.ARMOR,
    description:
      'Tempered hides reinforced with metal studs. Segmented armor that guards every stride.',
    value: 34,
    defense: 6,
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 6.75,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Runed Hood',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. A cloth hood shielding the eyes.',
    value: 40,
    defense: 5,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 7,
    slot: PlayerSlot.head,
  },
  {
    name: 'Runed Circlet',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. A circlet lined with thin plates.',
    value: 44,
    defense: 6,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 6.3,
    slot: PlayerSlot.head,
  },
  {
    name: 'Runed Helm',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. A rigid helm forged for battle.',
    value: 48,
    defense: 7,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 5.25,
    slot: PlayerSlot.head,
  },
  {
    name: 'Runed Tunic',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Layered fabrics stitched again and again.',
    value: 44,
    defense: 5,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 7,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Runed Jack',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Quilted layers reinforced with studs.',
    value: 48,
    defense: 6,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 6.3,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Runed Cuirass',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Rigid plates locked over a padded core.',
    value: 52,
    defense: 7,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 5.25,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Runed Wraps',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Cloth wraps tightened for every expedition.',
    value: 42,
    defense: 5,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 7,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Runed Bracers',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Leather bracers backed with metal.',
    value: 45,
    defense: 6,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 6.3,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Runed Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Full gauntlets guarding every finger.',
    value: 49,
    defense: 7,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 5.25,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Runed Boots',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Boots with extra stitching for long marches.',
    value: 43,
    defense: 5,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 7,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Runed Greaves',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Fitted greaves with hidden plates.',
    value: 46,
    defense: 6,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 6.3,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Runed Chausses',
    type: ItemType.ARMOR,
    description:
      'Etched with reinforcing sigils. Segmented armor that guards every stride.',
    value: 50,
    defense: 7,
    rarity: 'Superior',
    rank: 5,
    dropWeight: 5.25,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Frostguard Hood',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. A cloth hood shielding the eyes.',
    value: 60,
    defense: 6,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 5,
    slot: PlayerSlot.head,
  },
  {
    name: 'Frostguard Circlet',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. A circlet lined with thin plates.',
    value: 64,
    defense: 7,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 4.5,
    slot: PlayerSlot.head,
  },
  {
    name: 'Frostguard Helm',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. A rigid helm forged for battle.',
    value: 68,
    defense: 8,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 3.75,
    slot: PlayerSlot.head,
  },
  {
    name: 'Frostguard Tunic',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Layered fabrics stitched again and again.',
    value: 64,
    defense: 6,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 5,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Frostguard Jack',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Quilted layers reinforced with studs.',
    value: 68,
    defense: 7,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 4.5,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Frostguard Cuirass',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Rigid plates locked over a padded core.',
    value: 72,
    defense: 8,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 3.75,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Frostguard Wraps',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Cloth wraps tightened for every expedition.',
    value: 62,
    defense: 6,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 5,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Frostguard Bracers',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Leather bracers backed with metal.',
    value: 65,
    defense: 7,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 4.5,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Frostguard Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Full gauntlets guarding every finger.',
    value: 69,
    defense: 8,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 3.75,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Frostguard Boots',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Boots with extra stitching for long marches.',
    value: 63,
    defense: 6,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 5,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Frostguard Greaves',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Fitted greaves with hidden plates.',
    value: 66,
    defense: 7,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 4.5,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Frostguard Chausses',
    type: ItemType.ARMOR,
    description:
      'Infused with crystallized warding frost. Segmented armor that guards every stride.',
    value: 70,
    defense: 8,
    rarity: 'Rare',
    rank: 6,
    dropWeight: 3.75,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Umbral Hood',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. A cloth hood shielding the eyes.',
    value: 85,
    defense: 7,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 3,
    slot: PlayerSlot.head,
  },
  {
    name: 'Umbral Circlet',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. A circlet lined with thin plates.',
    value: 89,
    defense: 8,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.7,
    slot: PlayerSlot.head,
  },
  {
    name: 'Umbral Helm',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. A rigid helm forged for battle.',
    value: 93,
    defense: 9,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.25,
    slot: PlayerSlot.head,
  },
  {
    name: 'Umbral Tunic',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Layered fabrics stitched again and again.',
    value: 89,
    defense: 7,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 3,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Umbral Jack',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Quilted layers reinforced with studs.',
    value: 93,
    defense: 8,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.7,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Umbral Cuirass',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Rigid plates locked over a padded core.',
    value: 97,
    defense: 9,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.25,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Umbral Wraps',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Cloth wraps tightened for every expedition.',
    value: 87,
    defense: 7,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 3,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Umbral Bracers',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Leather bracers backed with metal.',
    value: 90,
    defense: 8,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.7,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Umbral Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Full gauntlets guarding every finger.',
    value: 94,
    defense: 9,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.25,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Umbral Boots',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Boots with extra stitching for long marches.',
    value: 88,
    defense: 7,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 3,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Umbral Greaves',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Fitted greaves with hidden plates.',
    value: 91,
    defense: 8,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.7,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Umbral Chausses',
    type: ItemType.ARMOR,
    description:
      'Shadow-treated armor that drinks in light. Segmented armor that guards every stride.',
    value: 95,
    defense: 9,
    rarity: 'Epic',
    rank: 7,
    dropWeight: 2.25,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Dragonscale Hood',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. A cloth hood shielding the eyes.',
    value: 120,
    defense: 8,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 2,
    slot: PlayerSlot.head,
  },
  {
    name: 'Dragonscale Circlet',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. A circlet lined with thin plates.',
    value: 124,
    defense: 9,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.8,
    slot: PlayerSlot.head,
  },
  {
    name: 'Dragonscale Helm',
    type: ItemType.ARMOR,
    description: 'Scales tempered in wyrmfire. A rigid helm forged for battle.',
    value: 128,
    defense: 10,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.5,
    slot: PlayerSlot.head,
  },
  {
    name: 'Dragonscale Tunic',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Layered fabrics stitched again and again.',
    value: 124,
    defense: 8,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 2,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Dragonscale Jack',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Quilted layers reinforced with studs.',
    value: 128,
    defense: 9,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.8,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Dragonscale Cuirass',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Rigid plates locked over a padded core.',
    value: 132,
    defense: 10,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.5,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Dragonscale Wraps',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Cloth wraps tightened for every expedition.',
    value: 122,
    defense: 8,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 2,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Dragonscale Bracers',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Leather bracers backed with metal.',
    value: 125,
    defense: 9,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.8,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Dragonscale Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Full gauntlets guarding every finger.',
    value: 129,
    defense: 10,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.5,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Dragonscale Boots',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Boots with extra stitching for long marches.',
    value: 123,
    defense: 8,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 2,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Dragonscale Greaves',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Fitted greaves with hidden plates.',
    value: 126,
    defense: 9,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.8,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Dragonscale Chausses',
    type: ItemType.ARMOR,
    description:
      'Scales tempered in wyrmfire. Segmented armor that guards every stride.',
    value: 130,
    defense: 10,
    rarity: 'Legendary',
    rank: 8,
    dropWeight: 1.5,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Celestial Hood',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. A cloth hood shielding the eyes.',
    value: 180,
    defense: 9,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.2,
    slot: PlayerSlot.head,
  },
  {
    name: 'Celestial Circlet',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. A circlet lined with thin plates.',
    value: 184,
    defense: 10,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.08,
    slot: PlayerSlot.head,
  },
  {
    name: 'Celestial Helm',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. A rigid helm forged for battle.',
    value: 188,
    defense: 11,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 0.9,
    slot: PlayerSlot.head,
  },
  {
    name: 'Celestial Tunic',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Layered fabrics stitched again and again.',
    value: 184,
    defense: 9,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.2,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Celestial Jack',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Quilted layers reinforced with studs.',
    value: 188,
    defense: 10,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.08,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Celestial Cuirass',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Rigid plates locked over a padded core.',
    value: 192,
    defense: 11,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 0.9,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Celestial Wraps',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Cloth wraps tightened for every expedition.',
    value: 182,
    defense: 9,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.2,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Celestial Bracers',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Leather bracers backed with metal.',
    value: 185,
    defense: 10,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.08,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Celestial Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Full gauntlets guarding every finger.',
    value: 189,
    defense: 11,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 0.9,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Celestial Boots',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Boots with extra stitching for long marches.',
    value: 183,
    defense: 9,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.2,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Celestial Greaves',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Fitted greaves with hidden plates.',
    value: 186,
    defense: 10,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 1.08,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Celestial Chausses',
    type: ItemType.ARMOR,
    description:
      'Forged for champions of the skyward courts. Segmented armor that guards every stride.',
    value: 190,
    defense: 11,
    rarity: 'Ascended',
    rank: 9,
    dropWeight: 0.9,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Mythwoven Hood',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. A cloth hood shielding the eyes.',
    value: 240,
    defense: 10,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.9,
    slot: PlayerSlot.head,
  },
  {
    name: 'Mythwoven Circlet',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. A circlet lined with thin plates.',
    value: 244,
    defense: 11,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.81,
    slot: PlayerSlot.head,
  },
  {
    name: 'Mythwoven Helm',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. A rigid helm forged for battle.',
    value: 248,
    defense: 12,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.68,
    slot: PlayerSlot.head,
  },
  {
    name: 'Mythwoven Tunic',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Layered fabrics stitched again and again.',
    value: 244,
    defense: 10,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.9,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Mythwoven Jack',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Quilted layers reinforced with studs.',
    value: 248,
    defense: 11,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.81,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Mythwoven Cuirass',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Rigid plates locked over a padded core.',
    value: 252,
    defense: 12,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.68,
    slot: PlayerSlot.chest,
  },
  {
    name: 'Mythwoven Wraps',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Cloth wraps tightened for every expedition.',
    value: 242,
    defense: 10,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.9,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Mythwoven Bracers',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Leather bracers backed with metal.',
    value: 245,
    defense: 11,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.81,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Mythwoven Gauntlets',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Full gauntlets guarding every finger.',
    value: 249,
    defense: 12,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.68,
    slot: PlayerSlot.arms,
  },
  {
    name: 'Mythwoven Boots',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Boots with extra stitching for long marches.',
    value: 243,
    defense: 10,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.9,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Mythwoven Greaves',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Fitted greaves with hidden plates.',
    value: 246,
    defense: 11,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.81,
    slot: PlayerSlot.legs,
  },
  {
    name: 'Mythwoven Chausses',
    type: ItemType.ARMOR,
    description:
      'Panoplies tuned for living legends. Segmented armor that guards every stride.',
    value: 250,
    defense: 12,
    rarity: 'Divine',
    rank: 10,
    dropWeight: 0.68,
    slot: PlayerSlot.legs,
  },
];

const BASE_ITEM_TEMPLATES: ItemTemplateSeed[] = [
  {
    name: 'Splintered Club',
    type: ItemType.WEAPON,
    description: 'A broken length of wood barely fit for a fight.',
    value: 1,
    damageRoll: '1d6',
    rarity: 'Trash',
    rank: 1,
    dropWeight: 14,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Stone Shard Knife',
    type: ItemType.WEAPON,
    description: 'A chipped shard lashed to a hilt; better than bare fists.',
    value: 2,
    damageRoll: '1d6',
    rarity: 'Trash',
    rank: 1,
    dropWeight: 12,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Rusty Dagger',
    type: ItemType.WEAPON,
    description: 'A pitted dagger favored by desperate highwaymen.',
    value: 4,
    damageRoll: '1d6',
    rarity: 'Common',
    rank: 2,
    dropWeight: 11,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Weathered Spear',
    type: ItemType.WEAPON,
    description: 'A splintered haft with a stubbornly sharp tip.',
    value: 6,
    damageRoll: '1d6',
    rarity: 'Common',
    rank: 2,
    dropWeight: 9,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Shortsword',
    type: ItemType.WEAPON,
    description: 'A basic shortsword. Reliable and cheap.',
    value: 10,
    damageRoll: '1d6',
    rarity: 'Common',
    rank: 3,
    dropWeight: 9,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Iron Quarterstaff',
    type: ItemType.WEAPON,
    description: 'A sturdy staff engraved with simple runes.',
    value: 12,
    damageRoll: '1d6',
    rarity: 'Common',
    rank: 3,
    dropWeight: 8,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Tempered Longsword',
    type: ItemType.WEAPON,
    description: 'A well-balanced blade favored by veteran guards.',
    value: 35,
    damageRoll: '1d8',
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 6,
    slot: PlayerSlot.weapon,
  },
  {
    name: "Hunter's Recurve Bow",
    type: ItemType.WEAPON,
    description: 'Curved limbs deliver a powerful, silent shot.',
    value: 32,
    damageRoll: '1d8',
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 5,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Ember Hatchet',
    type: ItemType.WEAPON,
    description: 'Warm to the touch and eager to spit sparks.',
    value: 34,
    damageRoll: '1d6',
    rarity: 'Uncommon',
    rank: 4,
    dropWeight: 4,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Skyglass Rapier',
    type: ItemType.WEAPON,
    description: 'A featherlight blade that slices the air itself.',
    value: 115,
    damageRoll: '1d8',
    rarity: 'Fine',
    rank: 5,
    dropWeight: 3.5,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Steel War Pick',
    type: ItemType.WEAPON,
    description: 'A narrow spike built to punch through armor plates.',
    value: 120,
    damageRoll: '1d8',
    rarity: 'Fine',
    rank: 5,
    dropWeight: 3.2,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Gilded Flail',
    type: ItemType.WEAPON,
    description: 'Twin weighted heads on a chain for brutal swings.',
    value: 125,
    damageRoll: '1d8',
    rarity: 'Superior',
    rank: 5,
    dropWeight: 3,
    slot: PlayerSlot.weapon,
  },
  {
    name: "Stormcaller's Blade",
    type: ItemType.WEAPON,
    description: 'Crackles with barely contained lightning.',
    value: 85,
    damageRoll: '1d10',
    rarity: 'Rare',
    rank: 6,
    dropWeight: 2.5,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Stoneheart Maul',
    type: ItemType.WEAPON,
    description: 'A hefty maul that tremors with each impact.',
    value: 120,
    damageRoll: '1d10',
    rarity: 'Rare',
    rank: 7,
    dropWeight: 2.15,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Serrated Pike',
    type: ItemType.WEAPON,
    description: 'A long pike with a barbed, wicked tip.',
    value: 115,
    damageRoll: '1d10',
    rarity: 'Rare',
    rank: 7,
    dropWeight: 2.1,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Dragonsoul Greatsword',
    type: ItemType.WEAPON,
    description: 'Forged from the bones of an ancient wyrm.',
    value: 150,
    damageRoll: '2d6',
    rarity: 'Epic',
    rank: 8,
    dropWeight: 2.4,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Eclipse Greatmace',
    type: ItemType.WEAPON,
    description: 'A weighty mace forged to crush shields in darkness.',
    value: 175,
    damageRoll: '2d6',
    rarity: 'Epic',
    rank: 8,
    dropWeight: 1.65,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Skysteel Glaive',
    type: ItemType.WEAPON,
    description: 'A polearm of light alloy that bites deep.',
    value: 165,
    damageRoll: '1d10',
    rarity: 'Epic',
    rank: 7,
    dropWeight: 1.55,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Celestial Warhammer',
    type: ItemType.WEAPON,
    description: 'Stars wink within the crystal atop this staff.',
    value: 145,
    damageRoll: '1d8',
    rarity: 'Epic',
    rank: 7,
    dropWeight: 1.8,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Worldrender Halberd',
    type: ItemType.WEAPON,
    description: 'Said to have split a continent in mythic wars.',
    value: 250,
    damageRoll: '1d12',
    rarity: 'Legendary',
    rank: 9,
    dropWeight: 0.9,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Helstorm Cleaver',
    type: ItemType.WEAPON,
    description: 'A massive cleaver that leaves storm scars in its wake.',
    value: 240,
    damageRoll: '2d8',
    rarity: 'Legendary',
    rank: 9,
    dropWeight: 0.7,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Astral Crusader',
    type: ItemType.WEAPON,
    description: 'A radiant greatsword that hums with celestial fervor.',
    value: 280,
    damageRoll: '2d8',
    rarity: 'Legendary',
    rank: 9,
    dropWeight: 0.75,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Dragonvein Greatblade',
    type: ItemType.WEAPON,
    description: 'A blade forged to channel ancestral draconic power.',
    value: 320,
    damageRoll: '2d8',
    rarity: 'Mythic',
    rank: 10,
    dropWeight: 0.65,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Titanfall Hammer',
    type: ItemType.WEAPON,
    description: 'Said to fell giants in a single, thunderous blow.',
    value: 360,
    damageRoll: '2d10',
    rarity: 'Mythic',
    rank: 10,
    dropWeight: 0.6,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Dawnforged Relic Blade',
    type: ItemType.WEAPON,
    description: 'Radiates ancient sunlight that burns through armor.',
    value: 380,
    damageRoll: '2d6',
    rarity: 'Artifact',
    rank: 10,
    dropWeight: 0.55,
    slot: PlayerSlot.weapon,
  },
  {
    name: 'Veilpiercer Lance',
    type: ItemType.WEAPON,
    description: 'Tuned to skewer foes across planes of existence.',
    value: 520,
    damageRoll: '2d10',
    rarity: 'Transcendent',
    rank: 10,
    dropWeight: 0.35,
    slot: PlayerSlot.weapon,
  },
];

export const ITEM_TEMPLATES: ItemTemplateSeed[] = [
  ...ARMOR_TEMPLATES,
  ...BASE_ITEM_TEMPLATES,
];

export const ITEM_RARITY_LOOKUP: Record<
  string,
  { rarity: ItemTemplateSeed['rarity']; dropWeight: number }
> = ITEM_TEMPLATES.reduce(
  (acc, template) => {
    acc[template.name] = {
      rarity: template.rarity,
      dropWeight: template.dropWeight,
    };
    return acc;
  },
  {} as Record<
    string,
    { rarity: ItemTemplateSeed['rarity']; dropWeight: number }
  >,
);
