import {
  AchievementCategory,
  AchievementConditionType,
  AchievementRewardType,
  AchievementScope,
} from '@mud/database';

export type AchievementDefinitionSeed = {
  id: string;
  name: string;
  description: string;
  category: AchievementCategory;
  scope: AchievementScope;
  isSecret?: boolean;
  isRepeatable?: boolean;
  broadcastOnUnlock?: boolean;
  broadcastTemplate?: string | null;
  rewardType?: AchievementRewardType;
  rewardValue?: string | null;
  conditionType?: AchievementConditionType;
  conditionKey?: string | null;
  conditionValue?: string | null;
};

export const BANK_IT_GOLD_THRESHOLD = 500;
export const BIG_HIT_DAMAGE_THRESHOLD = 60;

export const PLAYER_ACHIEVEMENT_DEFINITIONS: AchievementDefinitionSeed[] = [
  {
    id: 'R001',
    name: 'First Blood',
    description: 'Win your first raid.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalRaidWins',
    conditionValue: '1',
  },
  {
    id: 'R002',
    name: 'Raider',
    description: 'Finish 5 raids.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalRaidsFinished',
    conditionValue: '5',
  },
  {
    id: 'R003',
    name: 'Veteran Raider',
    description: 'Finish 25 raids.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalRaidsFinished',
    conditionValue: '25',
  },
  {
    id: 'R004',
    name: 'Hundred Runs',
    description: 'Finish 100 raids.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalRaidsFinished',
    conditionValue: '100',
  },
  {
    id: 'R005',
    name: 'Deep Diver',
    description: 'Reach depth 10.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.RECORD,
    conditionKey: 'maxRaidDepthReached',
    conditionValue: '10',
  },
  {
    id: 'R006',
    name: 'Abyss Walker',
    description: 'Reach depth 25.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.RECORD,
    conditionKey: 'maxRaidDepthReached',
    conditionValue: '25',
  },
  {
    id: 'R007',
    name: 'Bank It',
    description: `Finish a raid with at least ${BANK_IT_GOLD_THRESHOLD} banked gold.`,
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.EVENT,
    conditionKey: 'run.bankGold',
    conditionValue: String(BANK_IT_GOLD_THRESHOLD),
  },
  {
    id: 'R008',
    name: 'Risk Taker',
    description: 'Continue 3 times in one raid.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.EVENT,
    conditionKey: 'run.continues',
    conditionValue: '3',
  },
  {
    id: 'R009',
    name: 'Streak 3',
    description: 'Win 3 raids in a row.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.STREAK,
    conditionKey: 'bestWinStreak',
    conditionValue: '3',
  },
  {
    id: 'R010',
    name: 'Streak 10',
    description: 'Win 10 raids in a row.',
    category: AchievementCategory.RAID,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.STREAK,
    conditionKey: 'bestWinStreak',
    conditionValue: '10',
  },
  {
    id: 'C001',
    name: 'First Crit',
    description: 'Land your first critical hit.',
    category: AchievementCategory.COMBAT,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalCrits',
    conditionValue: '1',
  },
  {
    id: 'C002',
    name: 'Crit Machine',
    description: 'Land 100 critical hits.',
    category: AchievementCategory.COMBAT,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalCrits',
    conditionValue: '100',
  },
  {
    id: 'C003',
    name: 'Executioner',
    description: 'Kill 50 monsters.',
    category: AchievementCategory.COMBAT,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalKills',
    conditionValue: '50',
  },
  {
    id: 'C004',
    name: 'Warlord',
    description: 'Kill 500 monsters.',
    category: AchievementCategory.COMBAT,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalKills',
    conditionValue: '500',
  },
  {
    id: 'C005',
    name: 'Untouchable',
    description: 'Win a raid with 0 damage taken.',
    category: AchievementCategory.SECRET,
    scope: AchievementScope.PLAYER,
    isSecret: true,
    conditionType: AchievementConditionType.EVENT,
    conditionKey: 'run.damageTaken',
    conditionValue: '0',
  },
  {
    id: 'C006',
    name: 'Big Hit',
    description: `Deal at least ${BIG_HIT_DAMAGE_THRESHOLD} damage in one hit.`,
    category: AchievementCategory.SECRET,
    scope: AchievementScope.PLAYER,
    isSecret: true,
    conditionType: AchievementConditionType.EVENT,
    conditionKey: 'run.biggestHit',
    conditionValue: String(BIG_HIT_DAMAGE_THRESHOLD),
  },
  {
    id: 'E001',
    name: 'Shopper',
    description: 'Buy your first item.',
    category: AchievementCategory.ECONOMY,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalItemsPurchased',
    conditionValue: '1',
  },
  {
    id: 'E002',
    name: 'Big Spender',
    description: 'Spend 10,000 gold total.',
    category: AchievementCategory.ECONOMY,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalGoldSpent',
    conditionValue: '10000',
  },
  {
    id: 'E003',
    name: 'Collector',
    description: 'Equip 10 items.',
    category: AchievementCategory.ECONOMY,
    scope: AchievementScope.PLAYER,
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalItemsEquipped',
    conditionValue: '10',
  },
  {
    id: 'E004',
    name: 'Legendary',
    description: 'Buy a Legendary-tier item.',
    category: AchievementCategory.ECONOMY,
    scope: AchievementScope.PLAYER,
    broadcastOnUnlock: true,
    broadcastTemplate:
      '🏆 {playerName} just bought a *Legendary* item and unlocked *{achievementName}*!',
    conditionType: AchievementConditionType.THRESHOLD,
    conditionKey: 'totalLegendaryItemsPurchased',
    conditionValue: '1',
    rewardType: AchievementRewardType.BADGE,
    rewardValue: 'legendary-buyer',
  },
  {
    id: 'X001',
    name: 'Close Call',
    description: 'Finish a raid after surviving a round at 1 HP.',
    category: AchievementCategory.SECRET,
    scope: AchievementScope.PLAYER,
    isSecret: true,
    conditionType: AchievementConditionType.EVENT,
    conditionKey: 'run.closeCall',
    conditionValue: '1',
  },
  {
    id: 'X002',
    name: 'Greedy',
    description: 'Lose a raid after continuing 4 or more times.',
    category: AchievementCategory.SECRET,
    scope: AchievementScope.PLAYER,
    isSecret: true,
    conditionType: AchievementConditionType.EVENT,
    conditionKey: 'run.greedyLoss',
    conditionValue: '4',
  },
];
