name: Dependabot Automation

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dependabot:
    name: Manage Dependabot PRs
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve patch or security updates
        if: ${{ steps.metadata.outputs.update-type == 'security' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr review "$PR_URL" --approve --body "Automatically approved by Dependabot automation workflow."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for eligible updates
        if: ${{ steps.metadata.outputs.update-type == 'security' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge "$PR_URL" --auto --squash
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add automerge label for visibility
        if: ${{ steps.metadata.outputs.update-type == 'security' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr edit "$PR_URL" --add-label "automerge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
